# This is a basic workflow to help you get started with Actions

name: Build XMRig

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
  - cron: "0 13 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build on x86/arm v${{ matrix.arm_target }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arm_target: ['0', '7', '8']
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: xmrig/xmrig
          
      - name: Echo Version
        run: |
          echo "XMRIG_VERSION="`cat src/version.h | grep -Eo "APP_VERSION\s+\"(.+?)\"" | awk -F "\"" '{print $2}'`
